### ISSUE TITLE
I dunno

### ISSUE THREAD

**Issue by crogonint** [berengma/water_life#38]
It's done this like 5 times. Crashes the whole game. At first I thought the game thought I was drowning, even though damage is turned off. This time I actually read the thing, and I guess it's your mod doing it:

AsyncErr: ServerThread::run Lua: Runtime error from mod 'water_life' in callback luaentity_Step(): ...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:1472: attempt to index local 'node3' (a nil value)
stack traceback:
	...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:1472: in function 'is_in_deep'
	...est-5.3.0-win64\bin\..\mods\water_life/animals/shark.lua:67: in function 'logic'
	...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:940: in function <...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:921>

On a seperate note, are the seagulls in your mod? Because my seagulls keep trying to fly in the sand. Pretty morbid, actually.

**Comment by berengma** [comment]
step function is handled by mobkit, so it is a mobkit issue. See line 1472.

seagulls may crash into land from time to time. depends on server or machine lag.

**Comment by crogonint** [comment]
Apparently I did have an old mobkit. I guess the one in the GUI isn't current. I copied the code for one of the pages off of github.

Nah bro, the seagulls are trying to fly in the sand and ice a LOT, It's pretty morbid. I saw a couple of them successfully flying in the ocean, even. If there's a setting to change their elevation somehow, I'd love to know it. Preferrably before it traumatizes my neice. :D

**Comment by crogonint** [comment]
I'm going to change them immediately! Thank you so much!

...not sure about fixing it 'for me' though, as far as minecraft scripting goes, I don't know the coffee cup holder from the any key. ;)

Ground level is about +12 in most of the areas, and the ice and sand of course is like +1 to +3. I would say bare minimum would have to be +5 to keep them out of the shoreline, and that's if the logic is smart enough to keep them from flying in to a hillside. I'm going to try 15 as a minimum for me and my neice, but I think everybody would be just fine with a minimum of at least 5 or so.

By the way, thanks for a top notch add-on! Stuff like this is why I never messed with Minecraft. I knew that sooner or later, true artists would make their way on to the open source version to create amazing and astounding creations. :)

**Comment by crogonint** [comment]
Yeah, I don't see where it's defined static at all. Nead the beginning it local min to math.min (whatever that is), then in line 823 it does this:

function water_life.hq_climb(self,prty,fmin,fmax)
	if not max then max = 30 end
	if not min then min = 20 end

(should that say then fmax = 20 end?)

because line 873 does this:

function water_life.hq_glide(self,prty,fmin,fmax)
	if not max then fmax = 30 end
	if not min then fmin = 20 end

..but like I said, I've never mucked around with minetest scripting. I'm not about to muck around with a function, and I don't see a static setpoint, so..?

**Comment by crogonint** [comment]
Also, I notice that there is a fly section and a glide section. Fly appears to be using pitch, roll, etc. I don't think I've ever seen a gull change course, they occasionally shoot across the sky at a moderate clip, but generally I find them trying to fly through the sand or ice at an odd angle. When you hit them (mercy killing), are they supposed to roll to a 90 degree angle?

**Comment by berengma** [comment]
I am not going to teach you lua, nor the mintest api. You're on your own.

**Comment by crogonint** [comment]
... It's your mod that's busted. How's about you fix it?

That was a real dick thing to say, bruh. I spent time digging through your code to try to set it, and couldn't find it. I still don't know. I'm a newb at Minetest. No freaking idea where the setting might be. Could be in a config file.. Could be reached through the console. Hell it could be anywhere. Nobody knows where you put it but YOU.

Additionally, I thought maybe I might have found a typo. Maybe not, I dunno. That's why I asked. Did you answer?

No. Just told me I'm on my own.

Why would you even tell me I can set it, but not how??

WTH?

I've been browsing the forums, and I was kind of respecting you and what you were doing. Not now.

**Comment by crogonint** [comment]
FYI, I found your settings under 'all settings'.

It's not there either.

**Comment by LoneWolfHT** [comment]
Minetest docs: http://minetest-mods.github.io/
Lua Tutorial: https://www.lua.org/pil/1.html
Modding book: https://rubenwardy.com/minetest_modding_book/en/index.html

I don't see where they mentioned a setting to change fly heights. I see them giving you a tip about how to change it in the mod's code. You'll need knowledge of at least lua for that

Not sure if Discord is sacrilege for you or not but there's a modding channel in the Unofficial Minetest Discord where you can get help with modding if you're willing and trying to learn. There's also the Matrix/IRC chats too

**Comment by crogonint** [comment]
Thanks for the help, LoneWolf.

Just exactly why would Discord be sacrilege??
I didn't know there was a MineTest channel / server / whatever they want to
call it.

More irritated that a dev is treating a bug like it's a feature. I'm
willing to learn, if I need to though.

**Comment by LoneWolfHT** [comment]
> Thanks for the help, LoneWolf. Just exactly why would Discord be sacrilege?? I didn't know there was a MineTest channel / server / whatever they want to call it.

Some people won't touch a program unless it's open source. Here's the Discord link if you have Discord though https://discord.gg/6W84ytH

> More irritated that a dev is treating a bug like it's a feature. I'm willing to learn, if I need to though.

I think in this case they either don't have the problem or just don't consider it a bug :shrug:

**Comment by crogonint** [comment]
Well, I place a premium (preference if you will) on reputable open source
software, but in the real world, the open source base isn't big enough to
do EVERYTHING, yet. Microsoft and the rest of the 'evil empire' are slowly
losing their grip though, I'm quite pleased to be able to rely on
open-source for much more than I have been able to in the past. I think in
SUSE's hay-day (before they pissed everybody off by signing a treaty with
Microsoft) they were closer than we are today, but I think today the open
source community is more diversified, and able to answer more types of
challenges.

We still need to rely on closed source solutions to get from point A to
point B on occasion. Currently, anyway. ;)


I'll check out that MineTest channel when I get time to devote to it.
Thanks again!
