### ISSUE TITLE
Add Support for Hunger NG

### ISSUE THREAD

**Issue by daretmavi** [berengma/water_life#61]
Hi,
can you add support for Hunger NG?
If satiated, then healing is faster then poison damage.

Linuxdirk added support for this in his API
https://forum.minetest.net/viewtopic.php?p=385720#p385720
https://4w.gitlab.io/hunger_ng/README.API.html#change-hunger-effects
 - you can turn off healing `hunger_ng.set_effect('Playername', 'effect', 'setting')`

Thanx

**Comment by daretmavi** [comment]
Hi,

how is this implemented?

I tied the poison and I'm still getting healed quicker than poisoned.
Even the food is not giving any satiation.

**Comment by berengma** [comment]
I do not know about every mod in minetest universe. But water_life is open source, so feel free to fork and look for a solution.

**Comment by daretmavi** [comment]
This means, you did nothing to resolve this and just closed the issue? 
You could at least add some comment that you are not going to do anything. 
This is exactly what is driving new player away from minetest - mods not working together, developers not interested in interoperability.
I'm done, this is good mode and could be great if you could look after interoperability a little bit more. 
I wish you good luck.

**Comment by berengma** [comment]
if you need professional support better stick to paid software. I do this in my spare time and do not earn a single cent by doing so.

**Comment by daretmavi** [comment]
Sorry, I was a little bit depressed by the lack of communication.

It is not about "professional support" or money.
If I do something for community, then I care even more about interoperability between mods and listen to people.
If I do it for myself, then I don't care.

Take it as Feedback (if you want), that I like this mode, but it is hard to use it with other mods (I have to patch it).
(Fork is not always the answer - I'm not that good programmer)

**Comment by berengma** [comment]
Of course it is about professional support and money. :)
The only right I grant to community is to use my mod like said in the License file :)
It is me who controls what to do with my spare time not the community.
