### ISSUE TITLE
moskito plague

### ISSUE THREAD

**Issue by superfloh247** [berengma/water_life#76]
Hi,

I have an underground / cave area in a tropical biome - it's completely filled with moskitos.

What can I do to get rid of them? Are there mosquito eating animals / plants? Fire? Weapons?

**Comment by berengma** [comment]
There is a moskito repellant. And a setting. Please try reading first page in minetest forum. :smile:

**Comment by berengma** [comment]
https://forum.minetest.net/viewtopic.php?f=9&t=23436&hilit=water

**Comment by superfloh247** [comment]
Lots of lights did it. My place underground was just too dark.

**Comment by Adnan1091** [comment]
They are gone after you put a lot of light?Strange,it should be vice-versa as mosquitos are attracted to light.
