### ISSUE TITLE
wl_lb requires only interact

### ISSUE THREAD

**Issue by Bastrabun** [berengma/water_life#78]
The chatcommand wl_lb requires nothing but interact, but writes a whole list of biomes to the public chat.

In my opinion it should require server as well or send the list only to the player who sent the command

Suggest chatcommands.lua, line 80

privs = {interact = true},

change to 

privs = {server = true},

**Comment by berengma** [comment]
usually very few people know and try about available commands on a server. Is this really an issue?

**Comment by Bastrabun** [comment]
Someone must have found out on my server and we didn't know where that biome list came from for a while. It happened very occasionally and when I asked the players, noone knew what might have caused it. Even the one who used the command didn't step forward. So I thought it might have been a forgotten debug statement that only happens in rare cases.

The last few days, someone must have used it a couple more often times, so I feared for some real issue with mapgen, but then discovered it was actually a command :D That's the whole story.

It is an issue, but since it's so easy to override, you don't need to change if you don't want. I'll do it from the outside then.

**Comment by berengma** [comment]
Thats is easy to change, I will change to minetest.chat_send_player, so people can get some biome info without spamming global chat.

**Comment by berengma** [comment]
fixed
