### ISSUE TITLE
buoy entity can be separated from the node, leaving an immortal object.

### ISSUE THREAD

**Issue by fluxionary** [berengma/water_life#87]
1) Place a shark buoy. 
2) Drain all the water it sits on, so that the ball falls all the way down to its base. 
3) Destroy the buoy node. 
4) The ball will now remain, and you get the item back

**Comment by berengma** [comment]
lol, if this should be something I can fix from my mod, I will fix it. We do not want to pollute our drained oceans with immortal shark buoys, do we ?

**Comment by berengma** [comment]
fixed
