### ISSUE TITLE
deprecation warning with 5.8.0

### ISSUE THREAD

**Issue by fluxionary** [berengma/water_life#97]
```
WARNING[Main]: GenericCAO::addToScene(): Model water_life_crocodile.b3d loaded with 9 mesh buffers but only 1 texture(s) specified, this is deprecated.
```

**Comment by berengma** [comment]
deprecated means, starting with next major version increase not supported anymore. I will try to figure out what it means

**Comment by berengma** [comment]
croc model and texture updated

**Comment by fluxionary** [comment]
> croc model and texture updated

fantastic, thanks :) if you've got the time and energy for it, there's a similar issue w/ mobs_monster, but Tenplus1 doesn't know blender (and neither do i): https://codeberg.org/tenplus1/mobs_monster/issues/2

**Comment by berengma** [comment]
Unfortunately me neither. All my models have been donated by someone else. In case of the crocodile this is APercy. You can find him here on Github or in the forum as well.
